"""create nodes and edges tables

Revision ID: da1f3c1301da
Revises: a63c70faaba7
Create Date: 2026-08-09 19:28:55.775867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1f3c1301da'
down_revision: Union[str, Sequence[str], None] = 'a63c70faaba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mind_map_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mind_map_id'], ['mind_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_mind_map_id'), 'nodes', ['mind_map_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mind_map_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.UUID(), nullable=False),
    sa.Column('target', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('animated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mind_map_id'], ['mind_maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_mind_map_id'), 'edges', ['mind_map_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edges_mind_map_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_nodes_mind_map_id'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
