/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PresentMindMapIdRouteImport } from './routes/present.$mindMapId'
import { Route as WorkspaceMindMapIdRouteImport } from './routes/workspace.$mindMapId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentMindMapIdRoute = PresentMindMapIdRouteImport.update({
  id: '/present/$mindMapId',
  path: '/present/$mindMapId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceMindMapIdRoute = WorkspaceMindMapIdRouteImport.update({
  id: '/workspace/$mindMapId',
  path: '/workspace/$mindMapId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/present/$mindMapId': typeof PresentMindMapIdRoute
  '/workspace/$mindMapId': typeof WorkspaceMindMapIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/present/$mindMapId': typeof PresentMindMapIdRoute
  '/workspace/$mindMapId': typeof WorkspaceMindMapIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/present/$mindMapId': typeof PresentMindMapIdRoute
  '/workspace/$mindMapId': typeof WorkspaceMindMapIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/projects'
    | '/register'
    | '/settings'
    | '/templates'
    | '/present/$mindMapId'
    | '/workspace/$mindMapId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/projects'
    | '/register'
    | '/settings'
    | '/templates'
    | '/present/$mindMapId'
    | '/workspace/$mindMapId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/projects'
    | '/register'
    | '/settings'
    | '/templates'
    | '/present/$mindMapId'
    | '/workspace/$mindMapId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  PresentMindMapIdRoute: typeof PresentMindMapIdRoute
  WorkspaceMindMapIdRoute: typeof WorkspaceMindMapIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$mindMapId': {
      id: '/present/$mindMapId'
      path: '/present/$mindMapId'
      fullPath: '/present/$mindMapId'
      preLoaderRoute: typeof PresentMindMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$mindMapId': {
      id: '/workspace/$mindMapId'
      path: '/workspace/$mindMapId'
      fullPath: '/workspace/$mindMapId'
      preLoaderRoute: typeof WorkspaceMindMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  PresentMindMapIdRoute: PresentMindMapIdRoute,
  WorkspaceMindMapIdRoute: WorkspaceMindMapIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
